### ISSUE TITLE
PHP Notice on dev branch

### ISSUE THREAD

**Issue by silsbyc** [rrennick/shardb#1]
Thank you so much for updating for mysqli support and php7!

I am seeing a PHP Notice:
Undefined index: host in [...]/wp-content/db.php on line 217

**Comment by rrennick** [comment]
Thanks, I'll have a look at that tomorrow.

**Comment by rrennick** [comment]
https://github.com/rrennick/shardb/commit/a74965fc371efdbfe0ab040275d6f3745077379c

@silsbyc ready for testing.

**Comment by silsbyc** [comment]
Yes! PHP Warning not showing up anymore.

Thank you for the quick response.
