### ISSUE TITLE
shardb plugin aren’t closing the DB connections after being finished, and continue to create new ones

### ISSUE THREAD

**Issue by abdelkrim11** [rrennick/shardb#10]
I tried shardb plugin. It’s working. But aren’t closing the connections after being finished, and continue to create new ones. This cause max_user_connections limit error. The limit of max_user_connections i’m using is 128, the DBs are 16 + the global one.

The error -->   .PHP message: PHP Warning: mysqli_connect(): (HY000/1203): User USERNAME already has more than 'max_user_connections' active connections in PATH/wp-content/db.php on line 358PHP

**Comment by abdelkrim11** [comment]
It's working fine without woocommerce plugin. It looks like there is a conflict between woocommerce and shardb. The error is back when activating woocommerce again. Is there a specific woocommerce version required for the plugin to work without this error?

**Comment by rrennick** [comment]
> But aren’t closing the connections after being finished

The core WordPress database class does not automatically close DB connections. There is a [`$wpdb->close()`](https://github.com/WordPress/WordPress/blob/master/wp-includes/wp-db.php#L3656) function available for that if your application requires it.

> It's working fine without woocommerce plugin. It looks like there is a conflict between woocommerce and shardb.

A default `max_connections` value is probably insufficient for using WooCommerce in this context. WooCommerce more than doubles the number of tables per site. Try doubling your MySql max connections setting.

**Comment by abdelkrim11** [comment]
> The core WordPress database class does not automatically close DB connections. There is a [$wpdb->close()](https://github.com/WordPress/WordPress/blob/master/wp-includes/wp-db.php#L3656) function available for that if your application requires it.

Do i need to add it to db.php file? Where to i set this code? In which line? (I'm no a developer, i'm doing my best to learn and understand).

How can i use the Shardb plugin with muli servers and differant/same username like this example:

Host: server1.domain.com, DBname: prefix_0, Username: user1, password: pass1
.
.
.
Host: server16.domain.com, DBname: prefix_f, Username: user16, password: pass16
Host: server17.domain.com, DBname: prefix_global, Username: user17, password: pass17
Host: server18.domain.com, DBname: prefix_home, Username: user18, password: pass18
Host: server19.domain.com, DBname: prefix_vip1, Username: user19, password: pass19

I apreciate your help in advance.

**Comment by abdelkrim11** [comment]
> The core WordPress database class does not automatically close DB connections. There is a [$wpdb->close()](https://github.com/WordPress/WordPress/blob/master/wp-includes/wp-db.php#L3656) function available for that if your application requires it.

>Do i need to add it to db.php file? Where do i set this code? In which line? (I'm not a developer, i'm doing my best to learn and understand).

>How can i use the Shardb plugin with muli servers and differant/same username like this example:

>Host: server1.domain.com, DBname: prefix_0, Username: user1, password: pass1
.
.
.
Host: server16.domain.com, DBname: prefix_f, Username: user16, password: pass16
Host: server17.domain.com, DBname: prefix_global, Username: user17, password: pass17
Host: server18.domain.com, DBname: prefix_home, Username: user18, password: pass18
Host: server19.domain.com, DBname: prefix_vip1, Username: user19, password: pass19

>I apreciate your help in advance.

I'm waiting for a respond please!
