### ISSUE TITLE
Databse connection for escaping?

### ISSUE THREAD

**Issue by silsbyc** [rrennick/shardb#2]
Getting another PHP Notice (but I can't determine how it is affecting the database). The Notice doesn't say where the error is occurring.

PHP Notice:  SharDB was called <strong>incorrectly</strong>. SharDB must set a database connection for use with escaping.

**Comment by rrennick** [comment]
Thanks, do you get the message on the front end, dashboard or both? 

Escaping occurs prior to updating the DB so the warning is probably not affecting the DB in any way.

**Comment by silsbyc** [comment]
Both front end and dashboard. 

Thanks for calming my concerns about the DB.

**Comment by rrennick** [comment]
Should be fixed in https://github.com/rrennick/shardb/tree/develop.

**Comment by silsbyc** [comment]
Great! Thank you for your responsiveness to such an old (but so useful to our setup) plugin
